[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "miller"
version = "0.1.0"
dependencies = [
    "numpy >= 1.26.4",
    "matplotlib >= 3.9.2",
]

[project.scripts]
miller = "miller.__init__:main"